### ISSUE TITLE
VWTS问题

### ISSUE THREAD

**Issue by luobuyu** [lxily/Pcenter#1]
大佬，VWTS算法，pcb3038*的样例能跑通吗？

**Comment by lxily** [comment]
可以跑通, 刚添加了算例(^人^)

**Comment by lxily** [comment]
> 大佬，VWTS算法，pcb3038*的样例能跑通吗？

可以跑通, 刚添加了算例(^人^)

**Comment by luobuyu** [comment]
啊，多谢大佬，这么晚了还回复我！

**Comment by Zhouxing-Su** [comment]
难道不怕这份代码是钓鱼用的吗？

**Comment by luobuyu** [comment]
这份代码本来就不行啊！不过的点很多。
